[env:esp32-c3-mini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
upload_speed = 115200

lib_deps =
    https://github.com/Seeed-Studio/Grove_Gesture.git
    https://github.com/T-vK/ESP32-BLE-Keyboard.git

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
