[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

upload_port = COM8
monitor_port = COM8
monitor_speed = 115200

lib_deps =
    https://github.com/sparkfun/SparkFun_APDS-9960_Sensor_Arduino_Library.git